spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mydb2?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 200
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  redis:
    host: 192.168.56.10
    port: 6379
    password: wanglei123
    database: 0

    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
    serialization:
      fail-on-empty-beans: false
    property-naming-strategy: SNAKE_CASE